### ISSUE TITLE
libcint fails to compile with gcc 15.0.1

### ISSUE THREAD

**Issue by susilehtola** [sunqm/libcint#113]
libcint builds fail in the development version of Fedora (rawhide). This build root features the newest GCC compiler, version 15.0.1.

The error is caused by a number of failures in `cart2sph.c`:
```
make[2]: Leaving directory '/builddir/build/BUILD/libcint-6.1.2-build/libcint-6.1.2/aarch64-redhat-linux-gnu'
/builddir/build/BUILD/libcint-6.1.2-build/libcint-6.1.2/src/cart2sph.c:3892:9: error: initialization of ‘double * (*)(void)’ from incompatible pointer type ‘double * (*)(double *, int,  double *, int)’ [-Wincompatible-pointer-types]
 3892 |         s_bra_cart2spheric,
      |         ^~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/libcint-6.1.2-build/libcint-6.1.2/src/cart2sph.c:3892:9: note: (near initialization for ‘c2s_bra_sph[0]’)
/builddir/build/BUILD/libcint-6.1.2-build/libcint-6.1.2/src/cart2sph.c:3599:16: note: ‘s_bra_cart2spheric’ declared here
```
as well as
```
/builddir/build/BUILD/libcint-6.1.2-build/libcint-6.1.2/src/cart2sph.c: In function ‘c2s_sph_1e’:
/builddir/build/BUILD/libcint-6.1.2-build/libcint-6.1.2/src/cart2sph.c:4891:36: error: too many arguments to function ‘c2s_bra_sph[i_l]’; expected 0, have 4
 4891 |                 tmp1 = (c2s_bra_sph[i_l])(buf2, dj, tmp1, i_l);
      |                        ~~~~~~~~~~~~^~~~~~ ~~~~
```

**Comment by susilehtola** [comment]
There are also errors in `cint_bas.c`.

Full build log attached

[build.log](https://github.com/user-attachments/files/18617603/build.log)
